### PR TITLE
server command

### PR DESCRIPTION
**Pull request by tomdxw**
This is a work in progress. Please pull and test.

Note that you'll need to build the docker image before using it:

    cd whippet
    docker build -t thedxw/whippet-server-custom docker-images/whippet-server-custom

Then you can run "whippet server start" and you should have a server listening on localhost:8000. If you want to change that to "mymachine.local:8000" you can do:

    cd app-repo
    echo "<?php define('WP_SITEURL', 'http://mymachine.local:8000');" > config/server-local.php

# TODOs

- [x] Add a Dockerfile based on thedxw/whippet-server:tomdxw (that's my personal branch including some pull requests which haven't happened yet)
- [x] whippet server start -> starts processes in docker
- [x] whippet server ps -> runs docker ps -a and greps for relevant containers
- [x] whippet server logs (wordpress|mysql|mailcatcher) -> runs docker logs whippet_(wordpress|mysql|mailcatcher)
- [x] whippet server db connect -> runs interactive mysql prompt
- [x] whippet server db dump -> runs mysqldump
- [x] Add our dockerfile to docker hub and get it automatically built
- [x] Replacing "FROM thedxw/whippet-server" with "FROM php:apache" - this fixes an issue with nonces
- [x] whippet server stop
- [x] Make the output a bit more user-friendly instead of just printing docker's output
- [x] Do something sensible when a docker command fails instead of leaving everything in a broken state without explanation
- [x] Add a convenience function which shows the verbose output by default: "whippet server run" => "whippet server start && whippet server logs wordpress"
- [x] Rewrite the README
- [x] Use whippet-server as the base again (make sure the issue with nonces doesn't reappear)
- [x] Consider adding beanstalk, and setting BEANSTALKD_HOST automatically

# Nice-to-haves (turn into issues later)

- [ ] Change the image name we use to thedxw/whippet:apache
- [ ] Serve content from the public/ directory in an app
- [ ] Make it possible to run multiple instances of "whippet server" - right now the port number is hardcoded as 8000 and the non-data containers are run as "whippet_wordpress", "whippet_mysql" etc. - maybe we should store a list of containers in a .whippet.json file
- [ ] Consider rewriting the `server` command to be a wrapper around `docker-compose` (write a docker-compose.yml file to /tmp and replace all the complicated docker commands with `docker-compose up` etc)
- [ ] `db` issues
    - [ ] whippet server db connect 'select * from ...' (i.e. allow queries from the CLI so that the output can be piped, or it can be used in scripts)
    - [ ] Consider adding some method of exposing port 3306 of the mysql container (so that you don't need to go fiddling with `docker run` commands in order to connect to MySQL from outside of docker - something to discuss with Duncan)
    - [ ] combine `db` and `db undump` into one command (detect whether we're connected to STDIN or a pipe)
    - [ ] whippet server db connect - should keep a .mysql_history file (we could store that in app/.whippet/mysql_history and bind-mount it into the container? Or we could store it in the existing mysql data container)
- [ ] Use whippet-server instead of the php:apache image:
    - [ ] Resolve https://github.com/dxw/whippet-server/issues/33 and remove `:tomdxw` from `FROM thedxw/whippet-server:tomdxw`
    - [ ] Switch back to using whippet-server image as the base

### CODE REVIEW

**Comment by tomdxw** [comment]
@dgmstuart makes some good comments about keeping whippet-server a separate project in #8.

I think if whippet-server is to continue existing as a separate project we should probably either rename whippet or whippet-server as it'll be very confusing if "whippet-server" and "whippet server" are to co-exist.

**Comment by tomdxw** [comment]
I think everything listed under the TODO heading in the original comment is now done. Once this is merged I intend to file all the nice-to-haves as individual issues.

**Comment by tomdxw** [comment]
I'd like to rewrite the README before we merge this. Would be good to make it more of a tutorial than the current description of each command.

1. whippet server start
2. whippet server ps to verify that it's all running
3. if there are any errors - whippet server logs x
4. explain that non-Linux users may need to forward ports in VirtualBox
5. explain about setting WP_SITEURL

**Comment by tomdxw** [comment]
"whippet server" now uses "whippet-server" again. The README has been updated: https://github.com/dxw/whippet/tree/feature/server#run-your-application

There's also an undocumented "whippet server console" command which opens bash inside the whippet container. Mostly useful for editing core files during development.

Note that uploading files works, but for some reason at least on one site I was working on the attachments all inexplicably used https:// instead of http://.

Please experiment and feedback.

**Comment by harry-m** [comment]
Let's talk about this again - it's been a while since we looked at it.

**Comment by tomdxw** [comment]
And now `whippet server` is based on the `php:apache` docker image again. I was getting some weird error where auth cookies were set to expire as soon as they were set. It was weird.

I made that change over a week ago and it's been working perfectly ever since.

There's a lot of rough edges still, but I have an extensive list of nice-to-haves that can be made into issues once this is merged.

**Pull request merged**
