### PR TITLE
Display plugin inspections in dependencies output

### PR DESCRIPTION
**Pull request by dgmstuart**
When running `whippet deps install` or `whippet deps update` (which
does the install step as well as updating), output a link to any inspections
which dxw have done for that plugin and published on https://security.dxw.com/

Example:

```
[Checking plugins/akismet]
HEAD is now at 9ca38d7... v3.2
Inspections for this plugin:
* 13/07/2016 - Unknown - http://localhost:8000/plugins/advanced-custom-fields-table-field/
[Checking plugins/advanced-custom-fields-pro]
HEAD is now at 6fa6118... advanced-custom-fields-pro-5.4.8.zip
[WARNING] No inspections for this plugin
```

Merge Request for the API: https://git.govpress.com/dxw-advisories/app/merge_requests/15

I have some question marks over how/if this API is authenticated and how we handle that,
but it's hard to tell what's going on.

Three tasks remain - I think these can be deferred to further PRs:

- Including the inspection result in the output. This currently
  doesn't come back from the API, but it should be fairly easy to add it.
- Including error messages in output. Currently if an error arises while
  trying to retrieve and display an inspection, nothing is output.
  I considered stopping the installation running, but I don't think
  we want to stop whippet running e.g. if the API is down!
- Displaying multiple inspections. Currently if multiple inspections have
  been carried out over time, these have urls with incrementing numbers
  on the end, e.g. https://security.dxw.com/plugins/the-events-calendar-pro-2/
  One way of doing this would be to make multiple requests to the API: if you
  find one, keep incrementing the number until you can't find anymore.

Note: This was test-driven in the 'mockist' style of TDD:

1. start from somewhere near the top and assume the existence of collaborating
  objects (in this case all dependency-injected).
2. Mock out those collaborators in order to get the tests to your object to pass
3. Repeat all the way down until you reach the boundary of the system.

### CODE REVIEW

**Comment by tomdxw** [comment]
@dgmstuart Thanks for the PR.

Before looking at any code I notice a few issues:

- phpunit has been upgraded, meaning that it doesn't work with PHP 5.5. We cannot merge this right now as some servers still use PHP 5.5. We can either switch back to using the old version of phpunit, or we can just leave this PR alone for a few months (years?) until all the servers have been upgraded to Xenial which has PHP 7.0. (Third option: replace all the phpunit tests with peridot tests)
- It looks like there are 21 failing tests on PHP 7.0.
- The code needs to conform to the style checker. You can fix this very quickly by running: `vendor/bin/php-cs-fixer fix`

**Comment by dgmstuart** [comment]
@tomdxw cool

### Tests

The failing tests were due to the fact that paths aren't case sensitive on OSX, but are case sensitive on whatever Travis is running. Ick. 

So it was complaining about not being able to find `/Dxw/Whippet/Services/InspectionChecker` because it was in:

    src/services/InspectionChecker.php

and not 

    src/Services/InspectionChecker.php

### PHP version

It's a huge shame we can't use PhPUnit 5.4. The new `createMock()` method is much more than just a convenience method: it 'verifies' the doubles, ensuring that you can't mock something which doesn't exist, and also seems to check that mocked methods actually exist:

https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-5.4.0#new-features

Peridot looks nice and familiar to RSpec, but I'd be reluctant to rework _all_ of the tests into that other style. 

Maybe the pragmatic approach is to refactor to use the old-style of creating doubles (`getMock()`?). I don't know how different that is. 

### Style

I've fixed the style issues. Now the 5.6 and 7 builds are passing.

**Comment by dgmstuart** [comment]
@tomdxw One more note: there's one use of Heredoc in the specs - there's no indentation inside it, so maybe it's OK with your php indenting script? If not, feel free to revert that commit and fixup the following one.

**Comment by tomdxw** [comment]
> Maybe the pragmatic approach is to refactor to use the old-style of creating doubles (getMock()?). I don't know how different that is.

How about Mockery? That's what I've been using with Peridot tests.

**Comment by dgmstuart** [comment]
@tomdxw I've spoken to @Stretch96 (Chris), and there's an argument for not caring about PHP 5.5:

* The only action done with whippet on servers is `whippet deploy`
* There are currently no tests for deployment functionality
* There are some servers still on even older versions - back to 5.2

On the other hand, ops are aiming to have everything on 7 by the end of the year. The factor holding this up is that there are a bunch of sites on single-instances so upgrades need to be done out of hours.

**Comment by dgmstuart** [comment]
@tomdxw yeah, mockery looks like a good choice if it can run on old PHP and old PhpUnit

**Comment by tomdxw** [comment]
> The failing tests were due to the fact that paths aren't case sensitive on OSX, but are case sensitive on whatever Travis is running. Ick.

Actually it depends on the filesystem not the OS. macOS uses HFS+ by default at the moment. But APFS (Apple's new filesystem still in development) is case sensitive, I believe.

**Comment by tomdxw** [comment]
> The only action done with whippet on servers is whippet deploy

You can't run `whippet deploy` without first running `composer install`. So all servers running PHP 5.5 will be stuck on the current version of `whippet`. If we found a critical bug in `whippet deploy` we'd have to back-port the change.

> There are some servers still on even older versions - back to 5.2

Perhaps those servers running 5.2 don't host WP sites? If you tried to use whippet `master` on PHP 5.2, `composer install` would fail. Many many dependencies require PHP >= 5.5:

```
% composer show --tree | grep -- '--php ' | head
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
`--php >=5.3.0
   `--php >=5.2.0
`--php >=5.3.0
`--php >=5.5
|--php ^5.3.6 || >=7.0 <7.2
|  `--php >=5.3.3
|  |--php >=5.5.9
|  |  |--php >=5.5.9
|  |     `--php >=5.3.0
|     `--php >=5.3.3
```

> On the other hand, ops are aiming to have everything on 7 by the end of the year.

That's only a month. I think we can hold off until then.

**Comment by dgmstuart** [comment]
[Add a feature to whippet to query dxwsec for inspection results for installed plugins, and prompt when one needs a new inspection. Possibly use wp-json for the API?](https://trello.com/c/L2Wi4Qh8/10-add-a-feature-to-whippet-to-query-dxwsec-for-inspection-results-for-installed-plugins-and-prompt-when-one-needs-a-new-inspection)

**Comment by dgmstuart** [comment]
Closed in favour of https://github.com/dxw/whippet/pull/93

**Pull request closed without merging**
