### PR TITLE
Feature/theme management

### LINKED ISSUE #41: Theme management in Whippet
In order to remove submodules from site repos, we need to be able to manage themes using a "themes" file - in exactly the same way as plugins are currently managed.

There is a set of repos in GovPress github at wordpress-themes/2012,2013,2014 etc. The root repo URL for the themes file should be git@git.dxw.net:wordpress-themes/ (double check this).

As for plugins, existing themes in directories should be untouched. Whippet should only look at themes listed in the themes file.

When this is working, we'll start migrating sites over to this feature.

### PR DESCRIPTION
**Pull request by tomdxw**
This will fix #41. In progress.

Install:

- [x] Add a new module called `dependencies` or `deps`
- [x] `whippet deps install` reads from `whippet.lock` and installs the themes in the appropriate places
- [x] WhippetLock class should have a ::FromFile() static method and allow instantiating with a string of JSON
- [x] Produce the same useful output that `whippet plugins install` does
- [x] Do not install if there's a hash mismatch

Update:

- [x] `whippet deps update` reads from `whippet.json`, updates `whippet.lock` appropriately, and installs the themes
- [x] `whippet deps update` should modify the gitignore file too

Plugins:

- [x] Add plugins to `whippet.lock`
- [x] Add plugins to `whippet.json`
- [x] Make `whippet deps migrate` command

Loose ends:

- [x] Move WhippetLock to Files/WhippetLock
- [x] Use WhippetLock class for generating new whippet.lock file
- [x] Rename Dependencies(.*).php to Dependencies/$1.php (?)
- [x] Make sure each `->unwrap()` call has a `->isErr()` check
    - Dependencies/Installer->install
    - Dependencies/Updater->update (2)
    - Dependencies/Migration->migrate (2)
- [x] s/FileLocator/DirectoryLocator/
- [x] Pretty-print `whippet.lock` (see `JSON_PRETTY_PRINT`)
- [x] Pretty-print `whippet.json` when migrating
- [x] `dependencies install/update` should ignore `plugins` file entirely
- [x] `dependencies update` prints error
- [x] `dependencies install` doesn't produce any output, mysteriously
- [x] `$git->clone_repo()` fails
- [x] `$git->checkout()` fails
- [x] Run `whippet dependencies migrate/update` in all the projects, and see if anything breaks
- [x] Test missing file scenarios
- [x] Test broken JSON scenarios
- [x] Check gitignore behaviour
- [x] Test git command failure
- [x] Test invalid JSON scenarios
- [x] `PHP Warning:  file(/workbench/src/github.com/dxw/.gitignore): failed to open stream: No such file or directory in /workbench/src/github.com/dxw/whippet/src/Git/Gitignore.php on line 27`
- [x] Add Files/WhippetJson for parsing/generating whippet.json file
- [x] Test: a whippet.json file gets updated to remove a plugin, the plugin should be removed from .gitignore, but non-managed plugins should not
- [x] `migrate` should refuse to overwrite an existing `whippet.json` file
- [x] updater: return "whippet.json: file not found" instead of just "file not found"
- [x] Break up some of these very large functions into smaller ones
- [x] Make `deps` an alias for `dependencies`
- [x] Test for running `update` on `{"plugins":[{"name":"foo"}]}` - it'll produce a warning
- [x] Add deprecation notices to `whippet plugins` commands
- [x] Update `WhippetHelpers->whippet_init` to find the whippet directory when there's no `plugins` file
- [x] Update `deploy` (`Modules\Release`): if `whippet.json` exists then use `Dependencies\Install`, otherwise fallback to using `Modules\Plugin`
- [x] Make sure the other commands still work without `plugins` and `plugins.lock` files
- [x] Better tests: replace getFactory() with $this->addFactoryCallStatic(), $this->addFactoryInstantiate()
- [x] Replace DirectoryLocator with ProjectDirectory, which has a class method that returns a Result which contains a ProjectDirectory. It should just have one instance method: `->__toString()`
- [x] Update README

Make tickets (after this has been merged, or shortly before):

- [ ] Update individual dependencies, i.e.: `whippet deps update themes/twentysixteen`
- [ ] Change error messages: "whippet.lock not found" -> "whippet.lock not found. Have you run `whippet dependencies update`?"
- [ ] Repeating `['themes', 'plugins']` everywhere is not DRY
- [ ] Add `--no-install` to `whippet dependencies update` (if there's a need - there may not be)
- [ ] Remove `Module/Plugins`
    - Alias `whippet plugins install` => `whippet dependencies install`
    - Alias `whippet plugins upgrade` => `whippet dependencies update`
- [ ] `whippet migrate` (generator) needs to be updated to generate a `whippet.json` file instead of a `plugins` file
- [ ] Rewrite Gitignore as \Dxw\Whippet\Files\Gitignore (\Dxw\Whippet\Files\Base should be more generic, and \Dxw\Whippet\Files\Json should handle JSON files)
- [ ] stop hardcoding filenames everywhere
    - Files/Base::fromDir($dir) -> fromFile($dir . '/' . static::$fileName)
    - Files/Base->saveToDir($dir) -> saveToPath($dir . '/' . static::$fileName)
- [ ] Base.php: Ensure parsing the empty string (or non-arrays) as JSON causes an error
- [ ] `Notice: Undefined index: hash in /Users/chris/github-repos/whippet/src/Files/WhippetLock.php on line 18`

### CODE REVIEW

**Comment by tomdxw** [comment]
@harry-m Would you like to make sure it works?

Should be pretty self-explanatory, if you run `whippet plugins install/upgrade` it will tell you how to migrate and which commands you should be using instead.

(Oh yes... I just remembered I need to update the README. I'll add that to the list.)

**Comment by tomdxw** [comment]
The new README: https://github.com/dxw/whippet/tree/feature/theme-management

**Comment by harry-m** [comment]
@Stretch96 Please can you review/test this?

**Comment by harry-m** [comment]
NB see Tom's list of post-merge tasks in his main update above.

**Comment by Stretch96** [comment]
I've gone through the `whippet deps update` and `whippet deps install` commands so far, justs need to go through the `whippet migrate` command. Found a few uncaught errors, but it did work when I used it correctly :+1:

- phpunit fails with:
```
Fatal error: Class 'org\bovigo\vfs\vfsStream' not found in /Users/chris/github-repos/whippet/tests/Helpers.php on line 116
```
Adding `require 'vendor/autoload.php';` into `project_directory_test.php` passes the tests (Though it may be better to just include the one file needed for that class)

- Empty whippet.lock file, `whippet deps install` produces error:
```
Catchable fatal error: Argument 1 passed to Dxw\Whippet\Files\Base::__construct() must be of the type array, null given, called in /Users/chris/github-repos/whippet/src/Files/Base.php on line 14 and defined in /Users/chris/github-repos/whippet/src/Files/Base.php on line 26
```
Changing the check in Base.php to:
```
if (json_last_error() !== JSON_ERROR_NONE || !is_array($data))
```
Catches this error (I think it's because `json_decode('')` doesn't cause an error, it just returns NULL instead of an empty array)

- With `{}` in whippet.lock file  `whippet deps install` produces notice:
```
Notice: Undefined index: hash in /Users/chris/github-repos/whippet/src/Files/WhippetLock.php on line 18
```
changing line 18 in WhippetLock.php to:
```
return $this->data['hash'] ?? NULL;
```
Catches this

**Comment by tomdxw** [comment]
> phpunit fails with:

Did you run `phpunit` or `vendor/bin/phpunit`? If you run `vendor/bin/phpunit` then it already has the composer dependencies loaded.

(It's also useful for the Travis tests because we need to test 5.5 but the latest version of PHPUnit only supports 5.6 and 7.0).

> `return $this->data['hash'] ?? NULL;`

That's PHP 7 syntax. We can't use that *quite* yet.

Things to fix:

- [ ] Base.php: Ensure parsing the empty string (or non-arrays) as JSON causes an error
- [ ] `Notice: Undefined index: hash in /Users/chris/github-repos/whippet/src/Files/WhippetLock.php on line 18`

**Pull request merged**
