### PR TITLE
Use main branch by default

### PR DESCRIPTION
**Pull request by mallorydxw**
Resolves: https://...

- [ ] Version number has been incremented, according to [Semantic Versioning](https://semver.org/spec/v2.0.0.html) rules
- [x] Includes tests (if new features are introduced)
- [x] Commit message includes link to the ticket/issue
- [x] Changelog updated
- [ ] PR open against [dxw's Homebrew Tap](https://github.com/dxw/homebrew-tap/) to point the Whippet formula to the new version number

### CODE REVIEW

**Comment by CristinaRO** [comment]
There are conflicts in the changelog file, if you have any time to fix them. That doesn't mean I can provide an in-depth review, but hoping that one of the PHP devs might be more inclined to do so if the PR was ready to be merged.

**Review by RobjS — APPROVED** [review]
All looks good to me.

Just needs a rebase for the changelog, then we can get it merged and wrapped up in the next version release 👍

**Comment by RobjS** [comment]
@dxw-serena Please could you review this when you have the time? It was Mallory's PR originally, but I had to rebase the branch, so shouldn't be the reviewer. Thanks.

**Review by dxw-serena — APPROVED** [review]
Seems fine.

**Pull request merged**
