### PR TITLE
Adds removal of plugins that are not whippet managed or Git submodule…

### PR DESCRIPTION
**Pull request by Stretch96**
…s, when using the 'plugin install' command

Issue: https://github.com/dxw/whippet/issues/1

This removes plugins from the plugin directory, if they are not in the plugins file, or not a Git submodule.

### CODE REVIEW

**Comment by tomdxw** [comment]
@Stretch96 This one may need a rebase against #37 too.

**Comment by tomdxw** [comment]
@Stretch96 In addition to the rebase, there's an issue with this.

When I use `whippet deploy` to deploy a site it installs the plugins found in `plugins`/`plugins.lock`, and then it proceeds to remove all the other plugins:

```
[Removing combo] Plugins must either be whippet managed, or a Git submodule
[Removing document-repository-combo] Plugins must either be whippet managed, or a Git submodule
[Removing rssextra-widget] Plugins must either be whippet managed, or a Git submodule
[Removing sharebuttonsanywhere] Plugins must either be whippet managed, or a Git submodule
[Removing star-ratings] Plugins must either be whippet managed, or a Git submodule
Completed successfully
```

(These plugins are stored in the repository, not a submodule and not a git-ignored whippet-managed plugin).

I'm not sure how best to do this. Maybe use `git ls-files wp-content/plugins/my-plugin`? It gives output if the file is tracked in the current repo, and no output if it isn't.

**Comment by tomdxw** [comment]
@Stretch96 Have you seen #25? I had forgotten about that. Looks like we may just be able to add `git clean -dxff` to the deployment process and git will handle everything for us.

**Comment by tomdxw** [comment]
Let's put this on hold for the moment as the plugins module is being superceded by the dependencies module.

I think we can probably add `git clean -dxff` to the deploy module instead.

**Comment by tomdxw** [comment]
Actually, I'm a little wary of adding `git clean -dxff` as that's a very destructive command.

It'll be fine on a server where the clone is only ever used for deployment, but let's imagine Tom is just testing the `deploy` command by `cd`ing to a local copy of a repo and running `whippet deploy ~/x`.

How about we modify the `deploy` command thusly:

- [ ] `whippet deploy` will run `git clean -dxn` after it installs dependencies (check for untracked files, including those listed in .gitignore)
- [ ] take the output of that command and remove any dependencies found in `whippet.lock`
- [ ] if there is any output remaining, refuse to continue (with an explanation, a list of files, and a non-zero exit status)
- [ ] run `git clean -dxn` on each dependency, and if there is any output, refuse to continue
- [ ] (maybe) add a `--force` command to override the refusals

And then in chef, on our servers:

- [ ] run `git clean -dxff && git submodule foreach git clean -dxff` immediately before we run `whippet deploy`

@Stretch96 @harry-m Does this sound like a reasonable solution? It's kind of passing the buck, but it also seems like it's better practice to loudly complain about extra files than just delete them.

**Comment by harry-m** [comment]
Under what circumstances might the deploy fail because of unexpected files? It would be bad if that happened often, though I do agree it should happen if deploy finds a project in an unrecoverable state.

I would rather not have to remember to run separate things from Chef. If that commands needs running, can't the deploy command just run it?

**Comment by tomdxw** [comment]
> Under what circumstances might the deploy fail because of unexpected files?

According to the above proposal, it would fail if there was a plugin installed and it got uninstalled in the latest commit, which happens fairly often.

> If that commands needs running, can't the deploy command just run it?

As a compromise between not wanting to delete files by default, and not adding new commands to chef, we could add a `--clean` flag. If the `--clean` flag is present, it deletes all untracked files.

The only modification we'd need to make to chef would be to add `--clean` to the `whippet deploy` command. And as it requires an extra flag, nobody would accidentally run `whippet deploy` and destroy a bunch of files they didn't want to delete.

**Comment by harry-m** [comment]
If the main reason for doing this is to remove Whippet-managed plugins, then isn't it a reasonably safe bet that (although destructive) this is ok?

Is there a way we can scope the removal of files to things that are definitely inside Whippet-managed plugins? As if so, this is definitely safe, I think?

Keen not to unnecessarily complicate things.

**Comment by tomdxw** [comment]
> If the main reason for doing this is to remove Whippet-managed plugins, then isn't it a reasonably safe bet that (although destructive) this is ok?

That's the aim, but using `git clean -dxff` is not targeted. It will destroy everything.

> Is there a way we can scope the removal of files to things that are definitely inside Whippet-managed plugins?

That's not currently possible.

Consider:

```
git clone ... my-project
cd my-project
whippet deploy ...
git pull --no-ff
# whippet.json and whippet.lock get updated to remove a plugin
whippet deploy ...
```

The second time `whippet deploy` gets run, it has no idea what was in `whippet.json`/`whippet.lock` in the past. It only knows what's currently in those files.

What we could do to work around the limitation of not knowing the contents of the old `whippet.lock` file, is:

- `whippet deps install`: after installing dependencies: `mkdir -p .whippet && cp whippet.lock .whippet/old-whippet.lock`
- `whippet deps install`: before installing dependencies: if a plugin/theme is in `.whippet/old-whippet.lock` but not in `whippet.lock`, delete it

That's a little more complicated, but not much more.

But that will work for whippet-managed dependencies only, it won't remove submodules.

> Keen not to unnecessarily complicate things.

Me too. That's why I thought having chef run `git clean -dxff` was a good idea - it sidesteps having to make difficult decisions about what we remove.

**Comment by harry-m** [comment]
I think we may have had some miscommunication about what this is supposed to do. It's not the case that only a whippet-managed plugins or submoduled plugins are acceptable.

At any time, the plugins which should be present after a whippet 

Can we solve this thusly:

* Pull
* whippet deps install (or whatever it now is)
* Enumerate the plugins in the plugin directory
* Remove from the list:
  * anything that is in the lock file
  * anything that is in the git working tree
  * anything that is a git submodule
* delete whatever is left

I think a step at the end to check for any remaining untracked files and warn about them is sensible - agree we should not just delete them.

After this point, a ``whippet deploy`` should work correctly. ```whippet deploy``` should never remove any plugins. It should only copy what is in the repo into the release directory.

Alternatively: this might all just be wrong, in which case, the three of us should talk about it together.

**Comment by harry-m** [comment]
Is this still relevant?

**Comment by mallorydxw** [comment]
This is a change to the `plugins` module while we're using the `dependencies` module for installing dependencies now. So I think we can safely close it.

**Pull request closed without merging**
